### ISSUE TITLE
Package libav-tools is not available

### ISSUE THREAD

**Issue by nnachefski** [getwarped/s2i-minimal-notebook#1]
Attempting to build s2i-minimal-notebook and getting this:

Package libav-tools is not available, but is
--
  | referred to by another package. This may mean that the package is missing, has been obsoleted, or is only available from another source However the following packages replace it:   ffmpeg  E: Package 'libav-tools' has no installation candidate Removing intermediate container 4c5f956fd32a error: build error: The command '/bin/sh -c apt-get update &&     apt-get install -y --no-install-recommends libav-tools rsync &&     apt-get clean &&     rm -rf /var/lib/apt/lists/*' returned a non-zero code: 100

**Comment by GrahamDumpleton** [comment]
Addressed in new version, but the whole repository/image has also been marked as obsolete with warning it should not be used. This should really have been done a long time ago, or even at the outset made clear was an example only and shouldn't have been used with anyone interested creating their own.
